### ISSUE TITLE
!meetup edit Difference Output

### ISSUE THREAD

**Issue by qCzar** [hellos3b/sjbha-bot#10]
When editing a meetup, the bot shows what's been changed. When there's no change the bot outputs "diff." It wasn't immediately clear if there was an error, it'd be great if the bot said "No changes performed" or something along those lines if there are no changes to the meetup.

https://discordapp.com/channels/358442034790400000/358442118928400384/597523857636589578

**Comment by hellos3b** [comment]
Fixed in https://github.com/hellos3b/sjbha-bot/commit/88abf1c194022a2fbf6046cc4fe6ddc015754f5b
