### ISSUE TITLE
Editing a meetup via Website Changes Date & TIme

### ISSUE THREAD

**Issue by qCzar** [hellos3b/sjbha-bot#11]
When editing a meetup via the website link, the time is removed and the date moves forward a day.

1. `!meetup edit`

2. `{select meetup}`

3. `{click link to edit via web}`

**Comment by qCzar** [comment]
I assume it moves forward a day when the meetup is in the evening due to the known UTC issue. But the fact that it removes the time of the event is odd.

**Comment by hellos3b** [comment]
damn TIMEZONES
