### ISSUE TITLE
Inconsistent event RSVP emoji location

### ISSUE THREAD

**Issue by cheesejaguar** [hellos3b/sjbha-bot#2]
<img width="601" alt="screen shot 2018-08-28 at 8 17 56 am" src="https://user-images.githubusercontent.com/4625152/44732806-f82a3000-aa9a-11e8-8727-acd7875567cf.png">

Correct format is emoji's below the description, but this event has the emojis between the title and the description. Seeing that the event came in as separate posts, possible race condition between adding emojis & finishing the submission.

**Comment by cheesejaguar** [comment]
Root cause appears to be the use of javascript:
https://github.com/hellos3b/sjbha-bot/blob/master/bot/Meetup.js#L180-L212

**Comment by hellos3b** [comment]
Looks to be a race issue on discord's side, as I await between messages (async/await is used to handle rate limit errors). I'm assuming discord received both messages together and then just flipped a coin on which to send out first
