### ISSUE TITLE
Cancel Option

### ISSUE THREAD

**Issue by qCzar** [hellos3b/sjbha-bot#21]
When Editing or Mentioning Meetups, or when buying and selling stocks, it'd be great if maybe the first option (0) or the last option (n+1) was to cancel that action. Just to prevent the bot from listening for an event for however many minutes.

**Comment by hellos3b** [comment]
Not a bad idea. I think there's actually a "cancel" command it listens to, but adding it to the list would probably be better UX-wise

**Comment by hellos3b** [comment]
V2 has a cancel option built-in to the Utility now. will take some time to propagate to the rest of code base, but for now it exists
