### ISSUE TITLE
Error "Method Not Allowed" when editing or canceling a meetup

### ISSUE THREAD

**Issue by qCzar** [hellos3b/sjbha-bot#22]
When editing a meetup, the bot throws the error ":ohno: METHOD NOT ALLOWED". We were able to cancel a meetup and now it throws the same error when cancelling.

May be related to the Hapas meetup that hasn't been marked as "Completed/Finished/Past"

**Comment by hellos3b** [comment]
Fixed https://github.com/hellos3b/sjbha-bot/commit/6e3a6a6cfce959a050c97b279e548bcd1d73a938
