### ISSUE TITLE
Owner Transfer got auto assigned to me

### ISSUE THREAD

**Issue by qCzar** [hellos3b/sjbha-bot#6]
![screen shot 2018-11-30 at 2 31 34 pm](https://user-images.githubusercontent.com/12929124/49318535-c4054780-f4ad-11e8-9672-afb0bf033d7e.png)

Not sure if the !meetup transfer before it messed things up but it seems the bot completely skipped the "Transfer to" question. When I transferred it to Trucy I was asked who I'd like to transfer it too.

**Comment by hellos3b** [comment]
Oh, shit lol hmmm will look into it

**Comment by hellos3b** [comment]
Haven't seen it pop up since, closing
