### ISSUE TITLE
Downvote/Upvote Recording

### ISSUE THREAD

**Issue by rgajrawala** [hellos3b/sjbha-bot#7]
Not a bug but a suggestion. Have the bot record :downvote:/:upvote: reactions on messages and display stats like most downvoted/upvoted person/comment? Maybe reset every season? Or maybe even record all reactions in general?

**Comment by hellos3b** [comment]
Haha, like a karma system? That would be pretty funny, can add `!karma`

**Comment by hellos3b** [comment]
Not implementing
