### ISSUE TITLE
Strava getActivities() only pulls first page

### ISSUE THREAD

**Issue by hellos3b** [hellos3b/sjbha-bot#8]
The strava -> getActivities() api pulls all activities since a specific epoch, but only the first page. If a user has recorded more than 30 activities in the time frame, the new ones begin to clip off into the second page, making stats and calendar innacurate

**Comment by ingochris** [comment]
```
S  M  T  W  T  F  S
-  -  -  -  -  -  -  
-  -  -  -  -  X  -  
X  X  X  X  X  X  X  
X  X  X  X  X  X  X  
X  X  X  X  -  o  
```

should be 

```
S  M  T  W  T  F  S
-  -  -  -  -  -  -  
-  -  -  -  -  X  -  
X  X  X  X  X  X  X  
X  X  X  X  X  X  X  
X  X  X  X  X  X  
```

**Comment by hellos3b** [comment]
Fixed
